### PR TITLE
Rustfmt for readability

### PR DESCRIPTION
**Pull request by peckpeck**
This one should be a single commit with rusfmt

### CODE REVIEW

**Comment by peckpeck** [comment]
@ProgVal this one's the right one

**Comment by peckpeck** [comment]
should I wait for a merge to make a second PR or should I add more commits directly in this one ?

**Comment by ProgVal** [comment]
Please wait.

I'm waiting for Travis to complete the test, and it's taking some time, sorry.

**Comment by peckpeck** [comment]
sure, it's just a question about the way you prefer to organize your PR and reviews

**Pull request merged**
