### PR TITLE
Position for nom5

### PR DESCRIPTION
**Pull request by dalance**
I implemented `position` function for nom5 and modified the sample source code.
This is related to #30.

### CODE REVIEW

**Comment by ProgVal** [comment]
Great, thanks!

**Comment by ProgVal** [comment]
Oops, I just noticed it doesn't compile without `alloc` or `std`. You can fix that by making Token use references to strings instead of owned strings.

**Comment by dalance** [comment]
Thanks. I fixed it.

**Comment by ProgVal** [comment]
I merged your PR manually to squash the last two commits. Thanks!

**Comment by dalance** [comment]
Thanks!

**Pull request closed without merging**
