### PR TITLE
Implemented storing additional information about input source

### PR DESCRIPTION
**Pull request by orthoxerox**
Some of my worries (I'm not a seasoned Rustacean by any measure, and would appreciate your guidance):

- rustfmt rearranged some of the code that wasn't actually changed
- it's a breaking change for people who construct spans manually
- rustc didn't complain, but I'm not sure you can derive `Copy` from a struct that has a reference

### CODE REVIEW

**Comment by peckpeck** [comment]
Hello, any news on this subject ?

For my usage, I implemented a value based extra info instead of a reference.
This makes using LocatedSpanEx less painful since you don't have to explicitly specify the lifetime all the time. Moreover, you still can pass a reference if necessary.

I also got a version that works for nom 5 using @wycats patch.
Would you be interested in a PR for this ?

**Comment by ProgVal** [comment]
My main concern with this PR was breaking compatibility, but since we'll need to do a major version to support nom 5, this seems like a good time.

@peckpeck Were there merge conflicts when applying both patches?

**Comment by peckpeck** [comment]
yes

**Comment by peckpeck** [comment]
moreover mine is bit different since it doesn't contain the lifetime part

**Comment by ProgVal** [comment]
That would be nice. Could you send it as a set of small PRs? (with optionally a first one for rustfmt)

**Comment by peckpeck** [comment]
against fflorent/master ?

**Comment by ProgVal** [comment]
yes

**Comment by peckpeck** [comment]
Done for the first part, https://github.com/fflorent/nom_locate/pull/24
but then i need to wait for the merge before making next PR

**Comment by orthoxerox** [comment]
Feel free to close this one if @peckpeck's version is better.

**Comment by ProgVal** [comment]
Closing, as I just merged @peckpeck's version.

Thanks for the idea!

**Pull request closed without merging**
