### PR TITLE
Fix no std incompatability bug

### PR DESCRIPTION
**Pull request by In-line**

### CODE REVIEW

**Comment by ProgVal** [comment]
ping?

**Comment by vivekvpandya** [comment]
Can this be merged? I am hitting issue when using nom_locate in substrate code. Substrate requires no_std

**Comment by ProgVal** [comment]
@vivekvpandya Merged in #73 (this one had merge conflicts that GH couldn't solve).

Can you confirm it works for you before I release?

**Comment by vivekvpandya** [comment]
@ProgVal  thanks for such a quick response! Yes latest source from github fixes my issue. Thanks again!

**Comment by ProgVal** [comment]
Thanks. It's released on crates.io now

**Pull request closed without merging**
