### PR TITLE
Nom5 extrainfo

### PR DESCRIPTION
**Pull request by peckpeck**
First PR using rustfmt

### CODE REVIEW

**Comment by ProgVal** [comment]
lgtm, but could you use consistent spacing? (`<T: AtEof,U>` vs `<T: AsBytes, U>`)?

**Comment by ProgVal** [comment]
nvm, I just realized you ran rustfmt **after** your commit. It's ok then.

**Comment by ProgVal** [comment]
Oops, this PR broke tests. Could you send a new PR to fix them?

**Comment by peckpeck** [comment]
I'm very sorry, but i made a mistake, this one is not the one i intended to push
It is the one I used for experiments on nom4

**Comment by peckpeck** [comment]
you should probably revert it

**Comment by ProgVal** [comment]
Ok. I removed your commit from the history

**Comment by peckpeck** [comment]
replaced by https://github.com/fflorent/nom_locate/pull/26

**Pull request merged**
