### PR TITLE
Bump nom to v7

### PR DESCRIPTION
**Pull request by paolobarbolini**

### CODE REVIEW

**Comment by ProgVal** [comment]
Thanks!

I tried to fix a merge conflict with master (I changed the version in Cargo.toml there), but Github is being silly, can you resolve it in your branch?

Can you undo the minimum version changes? I don't see any reason to bump it.

**Comment by paolobarbolini** [comment]
> I tried to fix a merge conflict with master (I changed the version in Cargo.toml there), but Github is being silly, can you resolve it in your branch?

Fixed

> Can you undo the minimum version changes? I don't see any reason to bump it.

nom's readme says that the new MSRV is 1.48. Older versions are still supported but may break at any time. Since you're releasing a new major version there should be no issue in bumping the MSRV for this project too. See https://github.com/Geal/nom#rust-version-requirements

**Comment by ProgVal** [comment]
Ok then

**Comment by insou22** [comment]
Is this going to be pushed to crates.io anytime soon? :slightly_smiling_face:

**Comment by progval** [comment]
Done!

**Pull request merged**
