### PR TITLE
Add support for extra information to locatedspan

### PR DESCRIPTION
**Pull request by peckpeck**
A new struct LocatedSpanEx can contain this info.

See https://github.com/fflorent/nom_locate/pull/22 for a version using reference

### CODE REVIEW

**Comment by peckpeck** [comment]
Tests are missing

**Comment by peckpeck** [comment]
Updated

**Comment by peckpeck** [comment]
Note that for comparison I took the same approach as before, ie do not take extra into account when comparing items

**Comment by ProgVal** [comment]
Thanks!

**Pull request merged**
