### PR TITLE
Update to nom 6

### PR DESCRIPTION
**Pull request by vtavernier**
nom 6 is out of alpha and was released on Oct 31st, this PR updates nom_locate to use the new version.

### CODE REVIEW

**Review by ProgVal — COMMENTED** [review]
Thanks! That was fast! :)

Just one comment: what about `nom::Needed::new(1)` instead of `nom::Needed::Size(1usize.try_into().unwrap())`?

**Comment by vtavernier** [comment]
It's still work in progress though, good catch for the `Needed::new(1)`.

However the removal of some legacy macro-related stuff in nom broke the integration tests, still working on this though.

**Comment by ProgVal** [comment]
oh and could you also fix these build issues? https://travis-ci.org/github/fflorent/nom_locate/jobs/740645034

**Comment by ProgVal** [comment]
Oops, missed your message.

Thanks!

**Comment by vtavernier** [comment]
I did create the PR to have the CI run too, it's weird that the build status isn't reported here on GitHub?

**Comment by ProgVal** [comment]
Yeah, Travis stopped reporting status for this repo and others some time between 2020-09-27 and 2020-09-30. I reached out to them but didn't get an answer.

**Comment by ProgVal** [comment]
The examples are a lot more verbose without `ws!()` :(

but we don't have a choice I guess

**Pull request merged**
