### PR TITLE
update example in readme see issue #92

### PR DESCRIPTION
**Pull request by pontussjostedt**
Updates the example in README

### CODE REVIEW

**Comment by pontussjostedt** [comment]
I am having trouble validating that the first example works aswell. There is no named! macro in nom or nom_locate after looking on docs.rs. Should the first example be removed/updated?

**Comment by pontussjostedt** [comment]
Not sure if I should bump the version in the changelog to #4.2.1 and include the change in the same format as the other changes documented there.

**Comment by progval** [comment]
That's probably a leftover from an old `nom`

**Comment by progval** [comment]
Don't bother with the changelog, I update it myself when publishing a release

**Comment by pontussjostedt** [comment]
> That's probably a leftover from an old `nom`

So it should be removed then I assume. gimme a sec and I'll make another commit.

**Comment by progval** [comment]
Please update the example instead of removing it. The modern equivalent of `named!` is to define a regular function

**Comment by progval** [comment]
Thanks!

**Pull request merged**
