### PR TITLE
Add license text

### LINKED ISSUE #42: Request to add LICENCE file
Hi Florent,

We are hoping to use the nom_locate library in Google's Fuchsia OS. Is there any chance of adding a LICENCE file to the root directory? I would be happy to make the PR myself, if you let me know what the date and copyright owner should be.

Also, this is less important, but would it be possible to change the text in benches/benches.rs to something in the public domain? 

Thanks,
Reka

### PR DESCRIPTION
**Pull request by fflorent**
Fixes #42 

@ProgVal, do you agree?

### CODE REVIEW

**Comment by ProgVal** [comment]
you may want to add the top people here too: https://github.com/fflorent/nom_locate/graphs/contributors?type=a

**Comment by rekanorman** [comment]
Hi @fflorent, just checking in to see if there's any update on this?

**Comment by fflorent** [comment]
@rekanorman thanks for the reminder !

@ProgVal As they are not maintaining the library, I suggest to add both of us. In any case, I guess, it will be unfair :(.

**Comment by ProgVal** [comment]
Copyright is about who wrote the code, not who maintains it.

Either way, I'm fine with it.

**Comment by rekanorman** [comment]
@fflorent just another reminder :)

**Comment by fflorent** [comment]
@ProgVal I guess this is a bit unfair… Maybe we can change the author list later.

Also the contribution to this project isn't quantified only by lines of code or number of commits. Reviewing PR is also a valuable task.

**Pull request merged**
