### PR TITLE
Change text for copyright reasons

### PR DESCRIPTION
**Pull request by fflorent**
@ProgVal Does it seems OK to you? I chose a text in public domain for copyright reasons and this one for the number of diacritics (maybe this criterion is overkill though).

### CODE REVIEW

**Comment by ProgVal** [comment]
woops, good catch.

**Comment by fflorent** [comment]
@ProgVal Alright. Thus I guess I can merge? :)

**Comment by ProgVal** [comment]
Yes. sorry I meant to merge, but didn't check my click was actually received by Github

**Comment by fflorent** [comment]
Thanks for the review @ProgVal! 

Happy new year!
Florent

**Pull request merged**
